SELECT
DESCRIPTION
, at.CODETABLESID
, LONGDESCRIPTION
FROM TABLEENTRIES te 
LEFT JOIN AttributeTypes at ON te.CODETABLESID = at.CODETABLESID
ORDER BY DESCRIPTION

---

SELECT DISTINCT
*
FROM AttributeTypes at
LEFT JOIN TABLEENTRIES te ON te.CODETABLESID = at.CODETABLESID
ORDER BY DESCRIPTION

---

SELECT
*
FROM ConstituentAttributes