SELECT R.ID, R.Constituent_ID, R.FIRST_NAME, R.LAST_NAME, R.[DATE_LAST_CHANGED],

case
when R.PRIMARY_ADDRESSEE_EDIT = -1
then R.PRIMARY_ADDRESSEE
else
dbo.GetSalutation(R.PRIMARY_ADDRESSEE_ID,R.ID,'',0,0,0,getdate())
end as 'PRIMARY_ADDRESSEE',

case
when R.PRIMARY_SALUTATION_EDIT = -1
then R.PRIMARY_SALUTATION
else
dbo.GetSalutation(R.PRIMARY_SALUTATION_ID,R.ID,'',0,0,0,getdate())
end as 'PRIMARY_SALUTATION',

ADDSAL_TYPE.LONGDESCRIPTION as 'ADDSAL_TYPE_DESC',CS.SALUTATION_ID, CS.SEQUENCE, CS.EDITABLE,

case
when CS.EDITABLE = -1
then CS.SALUTATION
else
dbo.GetSalutation(CS.SALUTATION_ID,R.ID,'',0,0,0,getdate())
end as 'SALUTATION_CORRECT',
CS.SALUTATION as 'SALUTATION_FIELD_INCORRECT'

FROM [RECORDS] R
left outer join CONSTITUENT_SALUTATION AS CS ON R.ID=CS.CONSTIT_ID
left outer join TABLEENTRIES AS TE ON R.TITLE_1=TE.TABLEENTRIESID
left outer join TABLEENTRIES ADDSAL_TYPE on CS.SAL_TYPE=ADDSAL_TYPE.TABLEENTRIESID

ORDER BY CS.SEQUENCE